POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpaWtrYSIsImlkIjoiNWZkMzc4ZTYzYTZkZjQzNzkzOTZkMzY5IiwiaWF0IjoxNjA4Mjk5MTI5fQ.uMJEeNlZ-00dA3x35o7RGgdPv7klgjLmI3BQZTNNT6s

{
  "title": "hieno jou jou jou otsikko",
  "author": "hyvä kirjoittaja",
  "url": "http://url.com",
  "likes": "7"
}